### ISSUE TITLE
File recording external storage / udisk0

### ISSUE THREAD

**Issue by dan-alarcon** [xjxxjx1017/cordova-phonegap-android-sdcard-full-external-storage-access-library#1]
Hello, the plugin worked perfectly for me in the matter of reading, now how do I write files to the USB stick? I'm not succeeding. Could you give a suggestion for the novice here? I thank you

**Comment by xjxxjx1017** [comment]
Hi danmobilers,
My only suggestion is that have a look at [cordova-plugin-file](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/), it has provided file writing APIs for android already. I haven't tried it out myself yet, but I believe that's the only library you need.
Usually you need to convert the data you want to save into a blob, and then call FileWriter.write(blob) to save them in the memory card.
Cheers

**Comment by dan-alarcon** [comment]
Thanks!!!! :)
